use crate::material::tokens::color_role::ColorRole;
use crate::material::tokens::shape::ShapeRole;
use crate::material::tokens::typography::TypeRole;
use crate::material::tokens::units::{Dp, Opacity};

/// Token values used by this component.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tokens {
    pub active_indicator_color: ColorRole,
    pub active_indicator_height: Dp,
    pub caret_color: ColorRole,
    pub container_color: ColorRole,
    pub container_shape: ShapeRole,
    pub disabled_active_indicator_color: ColorRole,
    pub disabled_active_indicator_height: Dp,
    pub disabled_active_indicator_opacity: Opacity,
    pub disabled_container_color: ColorRole,
    pub disabled_container_opacity: Opacity,
    pub disabled_input_color: ColorRole,
    pub disabled_input_opacity: Opacity,
    pub disabled_label_color: ColorRole,
    pub disabled_label_opacity: Opacity,
    pub disabled_leading_icon_color: ColorRole,
    pub disabled_leading_icon_opacity: Opacity,
    pub disabled_supporting_color: ColorRole,
    pub disabled_supporting_opacity: Opacity,
    pub disabled_trailing_icon_color: ColorRole,
    pub disabled_trailing_icon_opacity: Opacity,
    pub error_active_indicator_color: ColorRole,
    pub error_focus_active_indicator_color: ColorRole,
    pub error_focus_caret_color: ColorRole,
    pub error_focus_input_color: ColorRole,
    pub error_focus_label_color: ColorRole,
    pub error_focus_leading_icon_color: ColorRole,
    pub error_focus_supporting_color: ColorRole,
    pub error_focus_trailing_icon_color: ColorRole,
    pub error_hover_active_indicator_color: ColorRole,
    pub error_hover_input_color: ColorRole,
    pub error_hover_label_color: ColorRole,
    pub error_hover_leading_icon_color: ColorRole,
    pub error_hover_supporting_color: ColorRole,
    pub error_hover_trailing_icon_color: ColorRole,
    pub error_input_color: ColorRole,
    pub error_label_color: ColorRole,
    pub error_leading_icon_color: ColorRole,
    pub error_supporting_color: ColorRole,
    pub error_trailing_icon_color: ColorRole,
    pub focus_active_indicator_color: ColorRole,
    pub focus_active_indicator_height: Dp,
    pub focus_input_color: ColorRole,
    pub focus_label_color: ColorRole,
    pub focus_leading_icon_color: ColorRole,
    pub focus_supporting_color: ColorRole,
    pub focus_trailing_icon_color: ColorRole,
    pub hover_active_indicator_color: ColorRole,
    pub hover_active_indicator_height: Dp,
    pub hover_input_color: ColorRole,
    pub hover_label_color: ColorRole,
    pub hover_leading_icon_color: ColorRole,
    pub hover_supporting_color: ColorRole,
    pub hover_trailing_icon_color: ColorRole,
    pub input_color: ColorRole,
    pub input_font: TypeRole,
    pub input_placeholder_color: ColorRole,
    pub input_prefix_color: ColorRole,
    pub input_suffix_color: ColorRole,
    pub label_color: ColorRole,
    pub label_font: TypeRole,
    pub leading_icon_color: ColorRole,
    pub leading_icon_size: Dp,
    pub supporting_color: ColorRole,
    pub supporting_font: TypeRole,
    pub trailing_icon_color: ColorRole,
    pub trailing_icon_size: Dp,
}

/// Returns authored token values for this component.
pub const fn filled_text_field() -> Tokens {
    Tokens {
        active_indicator_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        active_indicator_height: crate::material::tokens::units::Dp(f32::from_bits(0x3F800000)),
        caret_color: crate::material::tokens::color_role::ColorRole::Primary,
        container_color: crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        container_shape: crate::material::tokens::shape::ShapeRole::CornerExtraSmallTop,
        disabled_active_indicator_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_active_indicator_height: crate::material::tokens::units::Dp(f32::from_bits(0x3F800000)),
        disabled_active_indicator_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3EC28F5C,
        )),
        disabled_container_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_container_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3D23D70A)),
        disabled_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_input_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_label_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_label_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_leading_icon_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_supporting_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_supporting_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_trailing_icon_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_trailing_icon_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3EC28F5C,
        )),
        error_active_indicator_color: crate::material::tokens::color_role::ColorRole::Error,
        error_focus_active_indicator_color: crate::material::tokens::color_role::ColorRole::Error,
        error_focus_caret_color: crate::material::tokens::color_role::ColorRole::Error,
        error_focus_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        error_focus_label_color: crate::material::tokens::color_role::ColorRole::Error,
        error_focus_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        error_focus_supporting_color: crate::material::tokens::color_role::ColorRole::Error,
        error_focus_trailing_icon_color: crate::material::tokens::color_role::ColorRole::Error,
        error_hover_active_indicator_color:
            crate::material::tokens::color_role::ColorRole::OnErrorContainer,
        error_hover_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        error_hover_label_color: crate::material::tokens::color_role::ColorRole::OnErrorContainer,
        error_hover_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        error_hover_supporting_color: crate::material::tokens::color_role::ColorRole::Error,
        error_hover_trailing_icon_color: crate::material::tokens::color_role::ColorRole::OnErrorContainer,
        error_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        error_label_color: crate::material::tokens::color_role::ColorRole::Error,
        error_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        error_supporting_color: crate::material::tokens::color_role::ColorRole::Error,
        error_trailing_icon_color: crate::material::tokens::color_role::ColorRole::Error,
        focus_active_indicator_color: crate::material::tokens::color_role::ColorRole::Primary,
        focus_active_indicator_height: crate::material::tokens::units::Dp(f32::from_bits(0x40000000)),
        focus_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        focus_label_color: crate::material::tokens::color_role::ColorRole::Primary,
        focus_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        focus_supporting_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        focus_trailing_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        hover_active_indicator_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        hover_active_indicator_height: crate::material::tokens::units::Dp(f32::from_bits(0x3F800000)),
        hover_input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        hover_label_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        hover_leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        hover_supporting_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        hover_trailing_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        input_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        input_font: crate::material::tokens::typography::TypeRole::BodyLarge,
        input_placeholder_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        input_prefix_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        input_suffix_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        label_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        label_font: crate::material::tokens::typography::TypeRole::BodyLarge,
        leading_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        leading_icon_size: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
        supporting_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        supporting_font: crate::material::tokens::typography::TypeRole::BodySmall,
        trailing_icon_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        trailing_icon_size: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
    }
}
