use crate::material::tokens::color_role::ColorRole;
use crate::material::tokens::shape::ShapeRole;
use crate::material::tokens::typography::TypeRole;
use crate::material::tokens::units::{Dp, Opacity};

/// Token values used by this component.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tokens {
    pub active_container_opacity: Opacity,
    pub active_handle_height: Dp,
    pub active_handle_leading_space: Dp,
    pub active_handle_padding: Dp,
    pub active_handle_shape: ShapeRole,
    pub active_handle_trailing_space: Dp,
    pub active_handle_width: Dp,
    pub active_track_color: ColorRole,
    pub active_track_height: Dp,
    pub active_track_shape: ShapeRole,
    pub active_track_shape_leading: ShapeRole,
    pub disabled_active_track_color: ColorRole,
    pub disabled_active_track_opacity: Opacity,
    pub disabled_handle_color: ColorRole,
    pub disabled_handle_opacity: Opacity,
    pub disabled_handle_width: Dp,
    pub disabled_inactive_track_color: ColorRole,
    pub disabled_inactive_track_opacity: Opacity,
    pub disabled_stop_color: ColorRole,
    pub focus_active_track_color: ColorRole,
    pub focus_handle_width: Dp,
    pub focus_inactive_track_color: ColorRole,
    pub focus_stop_color: ColorRole,
    pub handle_color: ColorRole,
    pub handle_height: Dp,
    pub handle_shape: ShapeRole,
    pub handle_width: Dp,
    pub hover_handle_color: ColorRole,
    pub hover_handle_width: Dp,
    pub hover_stop_color: ColorRole,
    pub inactive_container_opacity: Opacity,
    pub inactive_track_color: ColorRole,
    pub inactive_track_height: Dp,
    pub inactive_track_shape: ShapeRole,
    pub label_container_color: ColorRole,
    pub label_text_color: ColorRole,
    pub pressed_active_track_color: ColorRole,
    pub pressed_handle_color: ColorRole,
    pub pressed_handle_width: Dp,
    pub pressed_inactive_track_color: ColorRole,
    pub pressed_stop_color: ColorRole,
    pub slider_active_handle_color: ColorRole,
    pub stop_indicator_color: ColorRole,
    pub stop_indicator_color_selected: ColorRole,
    pub stop_indicator_shape: ShapeRole,
    pub stop_indicator_size: Dp,
    pub stop_indicator_trailing_space: Dp,
    pub value_indicator_active_bottom_space: Dp,
    pub value_indicator_container_color: ColorRole,
    pub value_indicator_label_text_color: ColorRole,
    pub value_indicator_label_text_font: TypeRole,
}

/// Returns authored token values for this component.
pub const fn slider() -> Tokens {
    Tokens {
        active_container_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3F800000)),
        active_handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x42300000)),
        active_handle_leading_space: crate::material::tokens::units::Dp(f32::from_bits(0x40C00000)),
        active_handle_padding: crate::material::tokens::units::Dp(f32::from_bits(0x40C00000)),
        active_handle_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        active_handle_trailing_space: crate::material::tokens::units::Dp(f32::from_bits(0x40C00000)),
        active_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40800000)),
        active_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        active_track_height: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        active_track_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        active_track_shape_leading: crate::material::tokens::shape::ShapeRole::CornerFull,
        disabled_active_track_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_active_track_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_handle_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_handle_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3EC28F5C)),
        disabled_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40800000)),
        disabled_inactive_track_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_inactive_track_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3DF5C28F,
        )),
        disabled_stop_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        focus_active_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        focus_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40000000)),
        focus_inactive_track_color: crate::material::tokens::color_role::ColorRole::SecondaryContainer,
        focus_stop_color: crate::material::tokens::color_role::ColorRole::Primary,
        handle_color: crate::material::tokens::color_role::ColorRole::Primary,
        handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x42300000)),
        handle_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40800000)),
        hover_handle_color: crate::material::tokens::color_role::ColorRole::Primary,
        hover_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40800000)),
        hover_stop_color: crate::material::tokens::color_role::ColorRole::Primary,
        inactive_container_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3F800000)),
        inactive_track_color: crate::material::tokens::color_role::ColorRole::SecondaryContainer,
        inactive_track_height: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        inactive_track_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        label_container_color: crate::material::tokens::color_role::ColorRole::Primary,
        label_text_color: crate::material::tokens::color_role::ColorRole::InverseOnSurface,
        pressed_active_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        pressed_handle_color: crate::material::tokens::color_role::ColorRole::Primary,
        pressed_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x40000000)),
        pressed_inactive_track_color: crate::material::tokens::color_role::ColorRole::SecondaryContainer,
        pressed_stop_color: crate::material::tokens::color_role::ColorRole::Primary,
        slider_active_handle_color: crate::material::tokens::color_role::ColorRole::Primary,
        stop_indicator_color: crate::material::tokens::color_role::ColorRole::SecondaryContainer,
        stop_indicator_color_selected: crate::material::tokens::color_role::ColorRole::SecondaryContainer,
        stop_indicator_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        stop_indicator_size: crate::material::tokens::units::Dp(f32::from_bits(0x40800000)),
        stop_indicator_trailing_space: crate::material::tokens::units::Dp(f32::from_bits(0x40C00000)),
        value_indicator_active_bottom_space: crate::material::tokens::units::Dp(f32::from_bits(
            0x41400000,
        )),
        value_indicator_container_color: crate::material::tokens::color_role::ColorRole::InverseSurface,
        value_indicator_label_text_color: crate::material::tokens::color_role::ColorRole::InverseOnSurface,
        value_indicator_label_text_font: crate::material::tokens::typography::TypeRole::LabelLarge,
    }
}
