use crate::material::tokens::color_role::ColorRole;
use crate::material::tokens::shape::ShapeRole;
use crate::material::tokens::units::{Dp, Opacity};

/// Token values used by this component.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tokens {
    pub disabled_selected_handle_color: ColorRole,
    pub disabled_selected_handle_opacity: Opacity,
    pub disabled_selected_icon_color: ColorRole,
    pub disabled_selected_icon_opacity: Opacity,
    pub disabled_selected_track_color: ColorRole,
    pub disabled_track_opacity: Opacity,
    pub disabled_unselected_handle_color: ColorRole,
    pub disabled_unselected_handle_opacity: Opacity,
    pub disabled_unselected_icon_color: ColorRole,
    pub disabled_unselected_icon_opacity: Opacity,
    pub disabled_unselected_track_color: ColorRole,
    pub disabled_unselected_track_outline_color: ColorRole,
    pub focus_indicator_color: ColorRole,
    pub handle_shape: ShapeRole,
    pub pressed_handle_height: Dp,
    pub pressed_handle_width: Dp,
    pub selected_focus_handle_color: ColorRole,
    pub selected_focus_icon_color: ColorRole,
    pub selected_focus_track_color: ColorRole,
    pub selected_handle_color: ColorRole,
    pub selected_handle_height: Dp,
    pub selected_handle_width: Dp,
    pub selected_hover_handle_color: ColorRole,
    pub selected_hover_icon_color: ColorRole,
    pub selected_hover_track_color: ColorRole,
    pub selected_icon_color: ColorRole,
    pub selected_icon_size: Dp,
    pub selected_pressed_handle_color: ColorRole,
    pub selected_pressed_icon_color: ColorRole,
    pub selected_pressed_track_color: ColorRole,
    pub selected_track_color: ColorRole,
    pub state_layer_shape: ShapeRole,
    pub state_layer_size: Dp,
    pub track_height: Dp,
    pub track_outline_width: Dp,
    pub track_shape: ShapeRole,
    pub track_width: Dp,
    pub unselected_focus_handle_color: ColorRole,
    pub unselected_focus_icon_color: ColorRole,
    pub unselected_focus_track_color: ColorRole,
    pub unselected_focus_track_outline_color: ColorRole,
    pub unselected_handle_color: ColorRole,
    pub unselected_handle_height: Dp,
    pub unselected_handle_width: Dp,
    pub unselected_hover_handle_color: ColorRole,
    pub unselected_hover_icon_color: ColorRole,
    pub unselected_hover_track_color: ColorRole,
    pub unselected_hover_track_outline_color: ColorRole,
    pub unselected_icon_color: ColorRole,
    pub unselected_icon_size: Dp,
    pub unselected_pressed_handle_color: ColorRole,
    pub unselected_pressed_icon_color: ColorRole,
    pub unselected_pressed_track_color: ColorRole,
    pub unselected_pressed_track_outline_color: ColorRole,
    pub unselected_track_color: ColorRole,
    pub unselected_track_outline_color: ColorRole,
    pub icon_handle_height: Dp,
    pub icon_handle_width: Dp,
}

/// Returns authored token values for this component.
pub const fn switch() -> Tokens {
    Tokens {
        disabled_selected_handle_color: crate::material::tokens::color_role::ColorRole::Surface,
        disabled_selected_handle_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3F800000,
        )),
        disabled_selected_icon_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_selected_icon_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3EC28F5C,
        )),
        disabled_selected_track_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_track_opacity: crate::material::tokens::units::Opacity(f32::from_bits(0x3DF5C28F)),
        disabled_unselected_handle_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        disabled_unselected_handle_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3EC28F5C,
        )),
        disabled_unselected_icon_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        disabled_unselected_icon_opacity: crate::material::tokens::units::Opacity(f32::from_bits(
            0x3EC28F5C,
        )),
        disabled_unselected_track_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        disabled_unselected_track_outline_color: crate::material::tokens::color_role::ColorRole::OnSurface,
        focus_indicator_color: crate::material::tokens::color_role::ColorRole::Secondary,
        handle_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        pressed_handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x41E00000)),
        pressed_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x41E00000)),
        selected_focus_handle_color: crate::material::tokens::color_role::ColorRole::PrimaryContainer,
        selected_focus_icon_color: crate::material::tokens::color_role::ColorRole::OnPrimaryContainer,
        selected_focus_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        selected_handle_color: crate::material::tokens::color_role::ColorRole::OnPrimary,
        selected_handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
        selected_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
        selected_hover_handle_color: crate::material::tokens::color_role::ColorRole::PrimaryContainer,
        selected_hover_icon_color: crate::material::tokens::color_role::ColorRole::OnPrimaryContainer,
        selected_hover_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        selected_icon_color: crate::material::tokens::color_role::ColorRole::OnPrimaryContainer,
        selected_icon_size: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        selected_pressed_handle_color: crate::material::tokens::color_role::ColorRole::PrimaryContainer,
        selected_pressed_icon_color: crate::material::tokens::color_role::ColorRole::OnPrimaryContainer,
        selected_pressed_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        selected_track_color: crate::material::tokens::color_role::ColorRole::Primary,
        state_layer_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        state_layer_size: crate::material::tokens::units::Dp(f32::from_bits(0x42200000)),
        track_height: crate::material::tokens::units::Dp(f32::from_bits(0x42000000)),
        track_outline_width: crate::material::tokens::units::Dp(f32::from_bits(0x40000000)),
        track_shape: crate::material::tokens::shape::ShapeRole::CornerFull,
        track_width: crate::material::tokens::units::Dp(f32::from_bits(0x42500000)),
        unselected_focus_handle_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        unselected_focus_icon_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_focus_track_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_focus_track_outline_color: crate::material::tokens::color_role::ColorRole::Outline,
        unselected_handle_color: crate::material::tokens::color_role::ColorRole::Outline,
        unselected_handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        unselected_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        unselected_hover_handle_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        unselected_hover_icon_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_hover_track_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_hover_track_outline_color: crate::material::tokens::color_role::ColorRole::Outline,
        unselected_icon_color: crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_icon_size: crate::material::tokens::units::Dp(f32::from_bits(0x41800000)),
        unselected_pressed_handle_color: crate::material::tokens::color_role::ColorRole::OnSurfaceVariant,
        unselected_pressed_icon_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_pressed_track_color:
            crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_pressed_track_outline_color: crate::material::tokens::color_role::ColorRole::Outline,
        unselected_track_color: crate::material::tokens::color_role::ColorRole::SurfaceContainerHighest,
        unselected_track_outline_color: crate::material::tokens::color_role::ColorRole::Outline,
        icon_handle_height: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
        icon_handle_width: crate::material::tokens::units::Dp(f32::from_bits(0x41C00000)),
    }
}
