[package]
name = "shilpo"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
default-run = "shilpo"

[[bin]]
name = "shilpo"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
rust-embed = { version = "8.7.2", features = ["interpolate-folder-path", "include-exclude"] }
shilpo-ui.workspace = true
shilpo-device.workspace = true
shilpo-services.workspace = true
shilpo-theme-daemon.workspace = true
shilpo-ext-api.workspace = true
shilpo-ext-runtime.workspace = true
shilpo-observability.workspace = true

clap = { version = "4", features = ["derive", "env"] }
anyhow.workspace = true
libc.workspace = true
zbus.workspace = true
dirs.workspace = true
futures-lite.workspace = true
chrono.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "process", "signal", "sync"] }
log.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
notify.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_repr.workspace = true
semver.workspace = true
reqwest.workspace = true
image.workspace = true
resvg.workspace = true
sysinfo.workspace = true
fasteval = "0.2"
toml.workspace = true
toml_edit = "0.25"
schemars.workspace = true
niri-ipc.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile = "3"
