[package]
name = "shilpo-settings"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
shilpo-ui.workspace = true
shilpo-assets.workspace = true
shilpo-services.workspace = true
shilpo-device-protocol.workspace = true
shilpo-device-client.workspace = true
shilpo-theme.workspace = true
shilpo-theme-daemon.workspace = true
shilpo-config.workspace = true
shilpo-ext-api.workspace = true
shilpo-ext-runtime.workspace = true
futures-lite.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
niri-ipc.workspace = true
