[package]
name = "shilpo-services"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
niri-ipc.workspace = true
tokio.workspace = true
zbus.workspace = true
anyhow.workspace = true
futures-lite.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
dirs.workspace = true
smol.workspace = true
uuid = { workspace = true, features = ["v4"] }
libc = "0.2"
arboard = { version = "3", features = ["wayland-data-control"] }
shilpo-config = { path = "../config" }
shilpo-capture = { path = "../capture" }
notify.workspace = true
mcu-material-color.workspace = true
image.workspace = true
freedesktop-icons.workspace = true
