#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run

/** Regenerates checked-in WIT/schema artifacts from the canonical sources. */

import { dirname, fromFileUrl, join, resolve } from "@std/path";

const SCRIPT_DIR = dirname(fromFileUrl(import.meta.url));
const SDK_DIR = resolve(SCRIPT_DIR, "..");
const WIT_SOURCE = resolve(SDK_DIR, "../../core/ext-api/wit/extension.wit");
const SCHEMA_SOURCE = resolve(SDK_DIR, "../../core/ext-api/schema/extension-v1.schema.json");
const WIT_ADAPTER = resolve(SDK_DIR, "src/generated/wit.ts");
const MANIFEST_OUTPUT = resolve(SDK_DIR, "src/generated/manifest.ts");
const JCO_OUTPUT = resolve(SDK_DIR, "src/generated/jco");
const CHECK = Deno.args.includes("--check");

async function digest(path: string): Promise<string> {
  const bytes = await crypto.subtle.digest("SHA-256", await Deno.readFile(path));
  return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

async function run(command: string, args: string[]): Promise<void> {
  const result = await new Deno.Command(command, { args, stdout: "piped", stderr: "piped" })
    .output();
  if (!result.success) {
    throw new Error(new TextDecoder().decode(result.stderr));
  }
}

async function generateManifest(tempDir: string): Promise<string> {
  const output = join(tempDir, "manifest.ts");
  await run("npx", ["--yes", "json-schema-to-typescript@15", SCHEMA_SOURCE, "-o", output]);
  await run("deno", ["fmt", "--quiet", output]);
  return `// @generated by sdk/typescript/scripts/generate.ts
// Source: core/ext-api/schema/extension-v1.schema.json
// Generator: json-schema-to-typescript@15

${await Deno.readTextFile(output)}`;
}

async function generateJco(tempDir: string): Promise<void> {
  await run("npx", [
    "--yes",
    "@bytecodealliance/jco@1",
    "guest-types",
    WIT_SOURCE,
    "--world-name",
    "extension",
    "--strict",
    "--out-dir",
    tempDir,
  ]);
  await run("deno", ["fmt", "--quiet", tempDir]);
  const header =
    "// @generated by @bytecodealliance/jco@1\n// Source: core/ext-api/wit/extension.wit\n// Regenerate: deno task generate\n\n";
  for await (const entry of walkFiles(tempDir)) {
    if (entry.endsWith(".d.ts")) {
      await Deno.writeTextFile(entry, header + await Deno.readTextFile(entry));
    }
  }
}

async function* walkFiles(root: string): AsyncGenerator<string> {
  for await (const entry of Deno.readDir(root)) {
    const path = join(root, entry.name);
    if (entry.isDirectory) yield* walkFiles(path);
    else yield path;
  }
}

async function copyTree(source: string, target: string): Promise<void> {
  await Deno.mkdir(target, { recursive: true });
  for await (const entry of Deno.readDir(source)) {
    const from = join(source, entry.name);
    const to = join(target, entry.name);
    if (entry.isDirectory) await copyTree(from, to);
    else await Deno.copyFile(from, to);
  }
}

async function sameTree(left: string, right: string): Promise<boolean> {
  try {
    const leftEntries = [...Deno.readDirSync(left)].filter((entry) =>
      entry.isFile || entry.isDirectory
    );
    const rightEntries = [...Deno.readDirSync(right)].filter((entry) =>
      entry.isFile || entry.isDirectory
    );
    if (leftEntries.length !== rightEntries.length) return false;
    for (const entry of leftEntries) {
      const a = join(left, entry.name);
      const b = join(right, entry.name);
      if (entry.isDirectory) {
        if (!(await sameTree(a, b))) return false;
      } else if (await Deno.readTextFile(a) !== await Deno.readTextFile(b)) return false;
    }
    return true;
  } catch {
    return false;
  }
}

const tempDir = await Deno.makeTempDir({ prefix: "shilpo-sdk-generate-" });
try {
  const manifest = await generateManifest(tempDir);
  const jcoDir = join(tempDir, "jco");
  await generateJco(jcoDir);

  // The ergonomic adapter remains the stable runtime entrypoint, while the
  // complete JCO output is checked in as the ABI authority for type consumers.
  const wit = await Deno.readTextFile(WIT_ADAPTER);
  const witDigest = await digest(WIT_SOURCE);
  const withoutDigest = wit.replace(/^\/\/ Source SHA-256: .*\n/m, "");
  const adapter = `// Source SHA-256: ${witDigest}\n${withoutDigest}`;

  if (CHECK) {
    const currentManifest = await Deno.readTextFile(MANIFEST_OUTPUT);
    if (currentManifest !== manifest) throw new Error(`DRIFT: ${MANIFEST_OUTPUT}`);
    if (wit !== adapter) throw new Error(`DRIFT: ${WIT_ADAPTER}`);
    if (!(await sameTree(JCO_OUTPUT, jcoDir))) throw new Error(`DRIFT: ${JCO_OUTPUT}`);
    console.log("Check passed: generated WIT and schema artifacts are up to date.");
  } else {
    await Deno.writeTextFile(MANIFEST_OUTPUT, manifest);
    await Deno.writeTextFile(WIT_ADAPTER, adapter);
    await Deno.remove(JCO_OUTPUT, { recursive: true }).catch(() => {});
    await copyTree(jcoDir, JCO_OUTPUT);
    console.log("Generated WIT and schema artifacts from canonical sources.");
  }
} finally {
  await Deno.remove(tempDir, { recursive: true }).catch(() => {});
}
