// Static defaults, not dynamic semantic color roles.

/// An authored AndroidX ARGB value (0xAARRGGBB). No color conversion is performed.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DefaultArgb(pub u32);

/// Default light color values, kept distinct from semantic color roles.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LightPalette {
    pub background: DefaultArgb,
    pub error: DefaultArgb,
    pub error_container: DefaultArgb,
    pub inverse_on_surface: DefaultArgb,
    pub inverse_primary: DefaultArgb,
    pub inverse_surface: DefaultArgb,
    pub on_background: DefaultArgb,
    pub on_error: DefaultArgb,
    pub on_error_container: DefaultArgb,
    pub on_primary: DefaultArgb,
    pub on_primary_container: DefaultArgb,
    pub on_primary_fixed: DefaultArgb,
    pub on_primary_fixed_variant: DefaultArgb,
    pub on_secondary: DefaultArgb,
    pub on_secondary_container: DefaultArgb,
    pub on_secondary_fixed: DefaultArgb,
    pub on_secondary_fixed_variant: DefaultArgb,
    pub on_surface: DefaultArgb,
    pub on_surface_variant: DefaultArgb,
    pub on_tertiary: DefaultArgb,
    pub on_tertiary_container: DefaultArgb,
    pub on_tertiary_fixed: DefaultArgb,
    pub on_tertiary_fixed_variant: DefaultArgb,
    pub outline: DefaultArgb,
    pub outline_variant: DefaultArgb,
    pub primary: DefaultArgb,
    pub primary_container: DefaultArgb,
    pub primary_fixed: DefaultArgb,
    pub primary_fixed_dim: DefaultArgb,
    pub scrim: DefaultArgb,
    pub secondary: DefaultArgb,
    pub secondary_container: DefaultArgb,
    pub secondary_fixed: DefaultArgb,
    pub secondary_fixed_dim: DefaultArgb,
    pub surface: DefaultArgb,
    pub surface_bright: DefaultArgb,
    pub surface_container: DefaultArgb,
    pub surface_container_high: DefaultArgb,
    pub surface_container_highest: DefaultArgb,
    pub surface_container_low: DefaultArgb,
    pub surface_container_lowest: DefaultArgb,
    pub surface_dim: DefaultArgb,
    pub surface_tint: DefaultArgb,
    pub surface_variant: DefaultArgb,
    pub tertiary: DefaultArgb,
    pub tertiary_container: DefaultArgb,
    pub tertiary_fixed: DefaultArgb,
    pub tertiary_fixed_dim: DefaultArgb,
}

pub const DEFAULT_LIGHT: LightPalette = LightPalette {
    background: DefaultArgb(0xFFFEF7FF),
    error: DefaultArgb(0xFFB3261E),
    error_container: DefaultArgb(0xFFF9DEDC),
    inverse_on_surface: DefaultArgb(0xFFF5EFF7),
    inverse_primary: DefaultArgb(0xFFD0BCFF),
    inverse_surface: DefaultArgb(0xFF322F35),
    on_background: DefaultArgb(0xFF1D1B20),
    on_error: DefaultArgb(0xFFFFFFFF),
    on_error_container: DefaultArgb(0xFF410E0B),
    on_primary: DefaultArgb(0xFFFFFFFF),
    on_primary_container: DefaultArgb(0xFF21005D),
    on_primary_fixed: DefaultArgb(0xFF21005D),
    on_primary_fixed_variant: DefaultArgb(0xFF4F378B),
    on_secondary: DefaultArgb(0xFFFFFFFF),
    on_secondary_container: DefaultArgb(0xFF1D192B),
    on_secondary_fixed: DefaultArgb(0xFF1D192B),
    on_secondary_fixed_variant: DefaultArgb(0xFF4A4458),
    on_surface: DefaultArgb(0xFF1D1B20),
    on_surface_variant: DefaultArgb(0xFF49454F),
    on_tertiary: DefaultArgb(0xFFFFFFFF),
    on_tertiary_container: DefaultArgb(0xFF31111D),
    on_tertiary_fixed: DefaultArgb(0xFF31111D),
    on_tertiary_fixed_variant: DefaultArgb(0xFF633B48),
    outline: DefaultArgb(0xFF79747E),
    outline_variant: DefaultArgb(0xFFCAC4D0),
    primary: DefaultArgb(0xFF6750A4),
    primary_container: DefaultArgb(0xFFEADDFF),
    primary_fixed: DefaultArgb(0xFFEADDFF),
    primary_fixed_dim: DefaultArgb(0xFFD0BCFF),
    scrim: DefaultArgb(0xFF000000),
    secondary: DefaultArgb(0xFF625B71),
    secondary_container: DefaultArgb(0xFFE8DEF8),
    secondary_fixed: DefaultArgb(0xFFE8DEF8),
    secondary_fixed_dim: DefaultArgb(0xFFCCC2DC),
    surface: DefaultArgb(0xFFFEF7FF),
    surface_bright: DefaultArgb(0xFFFEF7FF),
    surface_container: DefaultArgb(0xFFF3EDF7),
    surface_container_high: DefaultArgb(0xFFECE6F0),
    surface_container_highest: DefaultArgb(0xFFE6E0E9),
    surface_container_low: DefaultArgb(0xFFF7F2FA),
    surface_container_lowest: DefaultArgb(0xFFFFFFFF),
    surface_dim: DefaultArgb(0xFFDED8E1),
    surface_tint: DefaultArgb(0xFF6750A4),
    surface_variant: DefaultArgb(0xFFE7E0EC),
    tertiary: DefaultArgb(0xFF7D5260),
    tertiary_container: DefaultArgb(0xFFFFD8E4),
    tertiary_fixed: DefaultArgb(0xFFFFD8E4),
    tertiary_fixed_dim: DefaultArgb(0xFFEFB8C8),
};

/// Default dark color values, kept distinct from semantic color roles.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DarkPalette {
    pub background: DefaultArgb,
    pub error: DefaultArgb,
    pub error_container: DefaultArgb,
    pub inverse_on_surface: DefaultArgb,
    pub inverse_primary: DefaultArgb,
    pub inverse_surface: DefaultArgb,
    pub on_background: DefaultArgb,
    pub on_error: DefaultArgb,
    pub on_error_container: DefaultArgb,
    pub on_primary: DefaultArgb,
    pub on_primary_container: DefaultArgb,
    pub on_primary_fixed: DefaultArgb,
    pub on_primary_fixed_variant: DefaultArgb,
    pub on_secondary: DefaultArgb,
    pub on_secondary_container: DefaultArgb,
    pub on_secondary_fixed: DefaultArgb,
    pub on_secondary_fixed_variant: DefaultArgb,
    pub on_surface: DefaultArgb,
    pub on_surface_variant: DefaultArgb,
    pub on_tertiary: DefaultArgb,
    pub on_tertiary_container: DefaultArgb,
    pub on_tertiary_fixed: DefaultArgb,
    pub on_tertiary_fixed_variant: DefaultArgb,
    pub outline: DefaultArgb,
    pub outline_variant: DefaultArgb,
    pub primary: DefaultArgb,
    pub primary_container: DefaultArgb,
    pub primary_fixed: DefaultArgb,
    pub primary_fixed_dim: DefaultArgb,
    pub scrim: DefaultArgb,
    pub secondary: DefaultArgb,
    pub secondary_container: DefaultArgb,
    pub secondary_fixed: DefaultArgb,
    pub secondary_fixed_dim: DefaultArgb,
    pub surface: DefaultArgb,
    pub surface_bright: DefaultArgb,
    pub surface_container: DefaultArgb,
    pub surface_container_high: DefaultArgb,
    pub surface_container_highest: DefaultArgb,
    pub surface_container_low: DefaultArgb,
    pub surface_container_lowest: DefaultArgb,
    pub surface_dim: DefaultArgb,
    pub surface_tint: DefaultArgb,
    pub surface_variant: DefaultArgb,
    pub tertiary: DefaultArgb,
    pub tertiary_container: DefaultArgb,
    pub tertiary_fixed: DefaultArgb,
    pub tertiary_fixed_dim: DefaultArgb,
}

pub const DEFAULT_DARK: DarkPalette = DarkPalette {
    background: DefaultArgb(0xFF141218),
    error: DefaultArgb(0xFFF2B8B5),
    error_container: DefaultArgb(0xFF8C1D18),
    inverse_on_surface: DefaultArgb(0xFF322F35),
    inverse_primary: DefaultArgb(0xFF6750A4),
    inverse_surface: DefaultArgb(0xFFE6E0E9),
    on_background: DefaultArgb(0xFFE6E0E9),
    on_error: DefaultArgb(0xFF601410),
    on_error_container: DefaultArgb(0xFFF9DEDC),
    on_primary: DefaultArgb(0xFF381E72),
    on_primary_container: DefaultArgb(0xFFEADDFF),
    on_primary_fixed: DefaultArgb(0xFF21005D),
    on_primary_fixed_variant: DefaultArgb(0xFF4F378B),
    on_secondary: DefaultArgb(0xFF332D41),
    on_secondary_container: DefaultArgb(0xFFE8DEF8),
    on_secondary_fixed: DefaultArgb(0xFF1D192B),
    on_secondary_fixed_variant: DefaultArgb(0xFF4A4458),
    on_surface: DefaultArgb(0xFFE6E0E9),
    on_surface_variant: DefaultArgb(0xFFCAC4D0),
    on_tertiary: DefaultArgb(0xFF492532),
    on_tertiary_container: DefaultArgb(0xFFFFD8E4),
    on_tertiary_fixed: DefaultArgb(0xFF31111D),
    on_tertiary_fixed_variant: DefaultArgb(0xFF633B48),
    outline: DefaultArgb(0xFF938F99),
    outline_variant: DefaultArgb(0xFF49454F),
    primary: DefaultArgb(0xFFD0BCFF),
    primary_container: DefaultArgb(0xFF4F378B),
    primary_fixed: DefaultArgb(0xFFEADDFF),
    primary_fixed_dim: DefaultArgb(0xFFD0BCFF),
    scrim: DefaultArgb(0xFF000000),
    secondary: DefaultArgb(0xFFCCC2DC),
    secondary_container: DefaultArgb(0xFF4A4458),
    secondary_fixed: DefaultArgb(0xFFE8DEF8),
    secondary_fixed_dim: DefaultArgb(0xFFCCC2DC),
    surface: DefaultArgb(0xFF141218),
    surface_bright: DefaultArgb(0xFF3B383E),
    surface_container: DefaultArgb(0xFF211F26),
    surface_container_high: DefaultArgb(0xFF2B2930),
    surface_container_highest: DefaultArgb(0xFF36343B),
    surface_container_low: DefaultArgb(0xFF1D1B20),
    surface_container_lowest: DefaultArgb(0xFF0F0D13),
    surface_dim: DefaultArgb(0xFF141218),
    surface_tint: DefaultArgb(0xFFD0BCFF),
    surface_variant: DefaultArgb(0xFF49454F),
    tertiary: DefaultArgb(0xFFEFB8C8),
    tertiary_container: DefaultArgb(0xFF633B48),
    tertiary_fixed: DefaultArgb(0xFFFFD8E4),
    tertiary_fixed_dim: DefaultArgb(0xFFEFB8C8),
};
