use super::{config_home, hex, write};
use crate::ui::theme::Theme;

// a btop theme file, which btop.conf points at
pub fn export(theme: &Theme) {
    let path = format!("{}/btop/themes/quickshell.theme", config_home());

    let background = hex(theme.background);
    let surface = hex(theme.surface);
    let selected = hex(theme.selected_surface);
    let border = hex(theme.border);
    let text = hex(theme.text);
    let secondary = hex(theme.secondary_text);
    let muted = hex(theme.muted_text);
    let accent = hex(theme.accent);
    let accent_hover = hex(theme.accent_hover);
    let success = hex(theme.success);
    let danger = hex(theme.danger);

    let entries = [
        ("main_bg", &background),
        ("main_fg", &text),
        ("title", &text),
        ("hi_fg", &accent),
        ("selected_bg", &selected),
        ("selected_fg", &text),
        ("inactive_fg", &muted),
        ("graph_text", &secondary),
        ("proc_misc", &accent_hover),
        ("cpu_box", &accent),
        ("mem_box", &success),
        ("net_box", &accent_hover),
        ("proc_box", &secondary),
        ("div_line", &border),
        ("temp_start", &success),
        ("temp_mid", &accent_hover),
        ("temp_end", &danger),
        ("cpu_start", &success),
        ("cpu_mid", &accent),
        ("cpu_end", &danger),
        ("free_start", &danger),
        ("free_mid", &accent),
        ("free_end", &success),
        ("cached_start", &surface),
        ("cached_mid", &accent),
        ("cached_end", &success),
        ("available_start", &danger),
        ("available_mid", &accent),
        ("available_end", &accent_hover),
        ("used_start", &success),
        ("used_mid", &accent),
        ("used_end", &danger),
        ("download_start", &muted),
        ("download_mid", &accent),
        ("download_end", &success),
        ("upload_start", &muted),
        ("upload_mid", &accent_hover),
        ("upload_end", &danger),
        ("process_start", &success),
        ("process_mid", &accent),
        ("process_end", &danger),
    ];

    let mut text = String::from("# generated by amane, do not edit\n");

    for (name, color) in entries {
        text.push_str(&format!("theme[{name}]=\"{color}\"\n"));
    }

    write(&path, &text);
}
