use std::fs;

use super::{config_home, hex};
use crate::ui::theme::Theme;

// a cava color theme; written in place, since cava watches the file itself
pub fn export(theme: &Theme) {
    let folder = format!("{}/cava/themes", config_home());

    let text = [
        String::from("# generated by amane, do not edit"),
        String::from("[color]"),
        format!("background = '{}'", hex(theme.background)),
        format!("foreground = '{}'", hex(theme.accent)),
        String::from("gradient = 1"),
        format!("gradient_color_1 = '{}'", hex(theme.success)),
        format!("gradient_color_2 = '{}'", hex(theme.accent)),
        format!("gradient_color_3 = '{}'", hex(theme.accent_hover)),
        format!("gradient_color_4 = '{}'", hex(theme.danger)),
    ];

    let _ = fs::create_dir_all(&folder);
    let _ = fs::write(format!("{folder}/quickshell"), text.join("\n") + "\n");
}
