use std::path::Path;

use amane::Color;

use super::{config_home, fill, hex, home, write};
use crate::ui::theme::{self, Theme};

const TEMPLATE: &str = include_str!("gtk.css");

const LIGHT: &str = "AmaneDynamicLight";
const DARK: &str = "AmaneDynamicDark";

// installed icon themes that match each mode, used when they are there
const LIGHT_ICONS: &str = "QuickshellSidebarLight";
const DARK_ICONS: &str = "QuickshellSidebarDark";

const YELLOW: Color = Color::rgb(0xf9, 0xe2, 0xaf);

/*
 * a light and a dark gtk theme, the one in use chosen through dconf, and
 * gtk 4's own stylesheet pointed at it, since libadwaita apps ignore themes
 */
pub fn export(theme: &Theme) {
    let data = std::env::var("XDG_DATA_HOME").unwrap_or_else(|_| format!("{}/.local/share", home()));

    for (name, light) in [(LIGHT, true), (DARK, false)] {
        let folder = format!("{data}/themes/{name}");

        let stylesheet = stylesheet(&theme::for_mode(Some(light)));

        write(&format!("{folder}/index.theme"), &index(name));
        write(&format!("{folder}/gtk-3.0/gtk.css"), &stylesheet);
        write(&format!("{folder}/gtk-4.0/gtk.css"), &stylesheet);
    }

    let (active, inactive, scheme, icons) = if theme.light {
        (LIGHT, DARK, "prefer-light", LIGHT_ICONS)
    } else {
        (DARK, LIGHT, "prefer-dark", DARK_ICONS)
    };

    let interface = "/org/gnome/desktop/interface";

    let icons_installed = Path::new(&format!("{data}/icons/{icons}")).exists();

    let icon_command = if icons_installed {
        format!("dconf write {interface}/icon-theme \"'{icons}'\";")
    } else {
        String::new()
    };

    let gtk4 = format!("{}/gtk-4.0", config_home());

    /*
     * switching away and back makes running gtk 3 apps read the rewritten
     * css; the portal restarts last so its file dialogs pick up gtk 4's
     */
    let script = format!(
        "dconf write {interface}/gtk-theme \"'{inactive}'\"; \
         dconf write {interface}/gtk-theme \"'{active}'\"; \
         {icon_command} \
         dconf write {interface}/color-scheme \"'{scheme}'\"; \
         sleep 0.8; mkdir -p '{gtk4}'; \
         ln -sfn '{data}/themes/{active}/gtk-4.0/gtk.css' '{gtk4}/gtk.css' && \
         sleep 0.2 && systemctl --user try-restart xdg-desktop-portal-gnome.service"
    );

    amane::spawn(&script);
}

fn stylesheet(theme: &Theme) -> String {
    let lightness = if theme.light { 0.42 } else { 0.70 };

    let yellow = theme::retone(theme::mix(YELLOW, theme.accent, 0.22), lightness, 0.48);

    let names = [
        ("@BACKGROUND@", hex(theme.background)),
        ("@SURFACE@", hex(theme.surface)),
        ("@ON_ACCENT@", hex(theme.on_accent)),
        ("@BORDER@", hex(theme.border)),
        ("@FOREGROUND@", hex(theme.text)),
        ("@MUTED@", hex(theme.secondary_text)),
        ("@ACCENT@", hex(theme.accent)),
        ("@SELECTION@", hex(theme.selected_surface)),
        ("@RED@", hex(theme.danger)),
        ("@GREEN@", hex(theme.success)),
        ("@YELLOW@", hex(yellow)),
    ];

    format!("/* generated by amane, do not edit */\n{}", fill(TEMPLATE, &names))
}

fn index(name: &str) -> String {
    format!(
        "[Desktop Entry]\nType=X-GNOME-Metatheme\nName={name}\n\
         Comment=Wallpaper-derived amane GTK theme\nEncoding=UTF-8\n\n\
         [X-GNOME-Metatheme]\nGtkTheme={name}\n"
    )
}
