use super::{hex, home, write};
use crate::ui::theme::Theme;

// css variables a spicetify theme reads from the cache folder
pub fn export(theme: &Theme) {
    let cache = std::env::var("XDG_CACHE_HOME").unwrap_or_else(|_| format!("{}/.cache", home()));

    let path = format!("{cache}/quickshell-theme/spotify.css");

    let scheme = if theme.light { "light" } else { "dark" };

    let variables = [
        ("background", theme.background),
        ("surface", theme.surface),
        ("surface-hover", theme.hover_surface),
        ("surface-pressed", theme.border),
        ("surface-selected", theme.selected_surface),
        ("text", theme.text),
        ("text-secondary", theme.secondary_text),
        ("text-muted", theme.muted_text),
        ("accent", theme.accent),
        ("accent-hover", theme.accent_hover),
        ("on-accent", theme.on_accent),
        ("positive", theme.success),
        ("negative", theme.danger),
    ];

    let mut text = format!("/* generated by amane, do not edit */\n:root {{\n  color-scheme: {scheme};\n");

    for (name, color) in variables {
        text.push_str(&format!("  --qs-{name}: {};\n", hex(color)));
    }

    text.push_str("}\n");

    write(&path, &text);
}
