use amane::Color;

use super::{config_home, hex, write};
use crate::ui::theme::{self, Theme};

// the seeds for the colors the shell's theme has no name for
const YELLOW: Color = Color::rgb(0xf9, 0xe2, 0xaf);
const MAGENTA: Color = Color::rgb(0xf5, 0xc2, 0xe7);
const CYAN: Color = Color::rgb(0x94, 0xe2, 0xd5);
const BLUE: Color = Color::rgb(0x89, 0xb4, 0xfa);

// the 16 ansi colors, and the few around them
struct Colors {
    background: Color,
    foreground: Color,
    selection: Color,
    cursor: Color,
    url: Color,
    ansi: [Color; 16],
}

// kitty and foot color files, and the open terminals recolored on the spot
pub fn export(theme: &Theme) {
    let colors = colors(theme);

    let folder = format!("{}/quickshell", config_home());

    let kitty = format!("{folder}/terminal-colors-kitty.conf");
    let foot = format!("{folder}/terminal-colors-foot.ini");

    write(&kitty, &kitty_config(theme, &colors));
    write(&foot, &foot_config(theme, &colors));

    reload_kitty(&kitty);
    recolor_foot(theme, &colors, &folder);
}

fn colors(theme: &Theme) -> Colors {
    let light = theme.light;

    // pulled toward the accent, so they sit with the rest of the theme
    let harmonize = |seed: Color, amount: f32| {
        let lightness = if light { 0.42 } else { 0.70 };

        theme::retone(theme::mix(seed, theme.accent, amount), lightness, 0.48)
    };

    // the dimmer first eight
    let regular = |color: Color| {
        let lightness = if light { 0.36 } else { 0.58 };

        theme::retone(color, lightness, 0.44)
    };

    let yellow = harmonize(YELLOW, 0.22);
    let magenta = harmonize(MAGENTA, 0.28);
    let cyan = harmonize(CYAN, 0.24);
    let blue = harmonize(BLUE, 0.30);

    Colors {
        background: theme.background,
        foreground: theme.text,
        selection: theme.selected_surface,
        cursor: theme.accent,
        url: blue,
        ansi: [
            theme.surface,
            regular(theme.danger),
            regular(theme.success),
            regular(yellow),
            regular(blue),
            regular(magenta),
            regular(cyan),
            theme.secondary_text,
            theme.muted_text,
            theme.danger,
            theme.success,
            yellow,
            blue,
            magenta,
            cyan,
            theme.text,
        ],
    }
}

fn kitty_config(theme: &Theme, colors: &Colors) -> String {
    let lines = [
        String::from("# generated by amane, do not edit"),
        format!("background {}", hex(colors.background)),
        format!("foreground {}", hex(colors.foreground)),
        format!("cursor {}", hex(colors.cursor)),
        format!("cursor_text_color {}", hex(theme.on_accent)),
        format!("selection_background {}", hex(colors.selection)),
        format!("selection_foreground {}", hex(colors.foreground)),
        format!("active_border_color {}", hex(colors.cursor)),
        format!("active_tab_background {}", hex(colors.cursor)),
        format!("active_tab_foreground {}", hex(theme.on_accent)),
        format!("inactive_tab_background {}", hex(colors.ansi[0])),
        format!("inactive_tab_foreground {}", hex(colors.ansi[8])),
        format!("tab_bar_background {}", hex(colors.ansi[0])),
    ];

    let mut text = lines.join("\n") + "\n";

    for (index, color) in colors.ansi.iter().enumerate() {
        text.push_str(&format!("color{index} {}\n", hex(*color)));
    }

    text
}

// the same colors under both of foot's themes, with the one in use picked
fn foot_config(theme: &Theme, colors: &Colors) -> String {
    let bare = |color: Color| hex(color).trim_start_matches('#').to_string();

    let initial = if theme.light { "light" } else { "dark" };

    let mut text = format!("# generated by amane, do not edit\n[main]\ninitial-color-theme={initial}\n");

    for section in ["dark", "light"] {
        text.push_str(&format!("[colors-{section}]\n"));
        text.push_str("alpha=0.75\n");
        text.push_str(&format!("background={}\n", bare(colors.background)));
        text.push_str(&format!("foreground={}\n", bare(colors.foreground)));
        text.push_str(&format!("selection-background={}\n", bare(colors.selection)));
        text.push_str(&format!("selection-foreground={}\n", bare(colors.foreground)));
        text.push_str(&format!("cursor={} {}\n", bare(colors.background), bare(colors.cursor)));
        text.push_str(&format!("urls={}\n", bare(colors.url)));

        for index in 0..8 {
            text.push_str(&format!("regular{index}={}\n", bare(colors.ansi[index])));
        }

        for index in 0..8 {
            text.push_str(&format!("bright{index}={}\n", bare(colors.ansi[index + 8])));
        }
    }

    text
}

// every kitty listens on a socket named after its pid
fn reload_kitty(path: &str) {
    let script = format!(
        "for pid in $(pgrep -f '^kitty( |$)'); do \
         kitty @ --to unix:@quickshell-kitty-$pid set-colors --all --configured '{path}'; \
         done 2>/dev/null"
    );

    amane::spawn(&script);
}

/*
 * foot only reads its colors at startup, so running ones are switched to the
 * right theme by signal and sent the new colors as escape codes on their tty
 */
fn recolor_foot(theme: &Theme, colors: &Colors, folder: &str) {
    let osc = |code: &str, value: String| format!("\x1b]{code};{value}\x07");

    let mut codes = osc("10", hex(colors.foreground));

    codes.push_str(&osc("11", hex(colors.background)));
    codes.push_str(&osc("12", hex(colors.cursor)));
    codes.push_str(&osc("17", hex(colors.selection)));
    codes.push_str(&osc("19", hex(colors.foreground)));

    for (index, color) in colors.ansi.iter().enumerate() {
        codes.push_str(&osc("4", format!("{index};{}", hex(*color))));
    }

    let codes_path = format!("{folder}/terminal-colors-foot.osc");

    write(&codes_path, &codes);

    let signal = if theme.light { "-USR2" } else { "-USR1" };

    let script = format!(
        "pkill {signal} -x foot 2>/dev/null; sleep 0.05; seen=' '; \
         for environment in /proc/[0-9]*/environ; do \
         if tr '\\0' '\\n' 2>/dev/null < \"$environment\" | grep -qx 'TERM=foot'; then \
         process=${{environment%/environ}}; tty=$(readlink \"$process/fd/1\" 2>/dev/null); \
         case \"$tty\" in /dev/pts/[0-9]*) \
         case \"$seen\" in *\" $tty \"*) ;; *) \
         seen=\"$seen$tty \"; cat '{codes_path}' > \"$tty\" 2>/dev/null ;; esac ;; esac; fi; done"
    );

    amane::spawn(&script);
}
