use super::{config_home, hex, write};
use crate::ui::theme::Theme;

// the status line and pane colors, sourced into every running tmux server
pub fn export(theme: &Theme) {
    let path = format!("{}/quickshell/tmux-colors.conf", config_home());

    let surface = hex(theme.surface);
    let hover = hex(theme.hover_surface);
    let border = hex(theme.border);
    let selected = hex(theme.selected_surface);
    let text = hex(theme.text);
    let secondary = hex(theme.secondary_text);
    let muted = hex(theme.muted_text);
    let accent = hex(theme.accent);
    let on_accent = hex(theme.on_accent);
    let danger = hex(theme.danger);

    let lines = [
        String::from("# generated by amane, do not edit"),
        format!("set -g status-style \"bg={surface},fg={text}\""),
        format!("set -g status-left-style \"bg={accent},fg={on_accent},bold\""),
        format!("set -g status-right-style \"bg={surface},fg={secondary}\""),
        format!("set -g window-status-style \"bg={surface},fg={muted}\""),
        format!("set -g window-status-current-style \"bg={selected},fg={text},bold\""),
        format!("set -g window-status-activity-style \"bg={hover},fg={accent},bold\""),
        format!("set -g window-status-bell-style \"bg={danger},fg={on_accent},bold\""),
        format!("set -g message-style \"bg={selected},fg={text}\""),
        format!("set -g message-command-style \"bg={selected},fg={accent}\""),
        format!("set -g mode-style \"bg={accent},fg={on_accent},bold\""),
        format!("set -g pane-border-style \"fg={border}\""),
        format!("set -g pane-active-border-style \"fg={accent}\""),
        format!("set -g clock-mode-colour \"{accent}\""),
        format!("set -g display-panes-colour \"{muted}\""),
        format!("set -g display-panes-active-colour \"{accent}\""),
    ];

    write(&path, &(lines.join("\n") + "\n"));

    // no server running is fine, the next one sources the file from its config
    let _ = amane::output(&format!("tmux source-file '{path}' 2>/dev/null"));
}
