[package]
name = "shilpo-capture"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
shilpo-ui.workspace = true
shilpo-assets.workspace = true
shilpo-config.workspace = true
arboard = { version = "3", features = ["wayland-data-control"] }

anyhow.workspace = true
chrono.workspace = true
dirs.workspace = true
futures-lite.workspace = true
image.workspace = true
libc.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }
zbus.workspace = true
ashpd.workspace = true
wayland-client.workspace = true
wayland-backend.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true

ffmpeg.workspace = true
ffmpeg-sys.workspace = true
pipewire.workspace = true
spa = { package = "libspa", version = "0.10" }
drm.workspace = true
mio.workspace = true

[dev-dependencies]
tempfile = "3"
