/**
 * Shilpo Extension TypeScript SDK (@shilpo/ext-sdk)
 *
 * Official TypeScript SDK for building sandboxed WebAssembly extensions
 * for the Shilpo Linux desktop environment.
 */

export type {
  ActionsHost,
  Activation,
  ActivationId,
  ActivationInput,
  ActivationOrigin,
  Alignment,
  BadgeNode,
  BarMenuClosedPayload,
  BarMenuCloseReason,
  BarMenuOpenedPayload,
  ButtonNode,
  Caller,
  CanonicalId,
  ClipboardHost,
  ContainerDirection,
  ContainerNode,
  ContributionId,
  DeactivateReason,
  Deadline,
  ErrorKind,
  ErrorPayload,
  EventKind,
  ExtensionEvent,
  ExtensionId,
  FilesystemHost,
  HttpHost,
  HttpRequest,
  HttpResponseEvent,
  IconButtonNode,
  IconNode,
  ImageNode,
  InputEvent,
  Justification,
  ListNode,
  LoadingIndicatorNode,
  LocationHost,
  LocationResponseEvent,
  MediaEvent,
  MountedEvent,
  NetworkEvent,
  NotificationRequest,
  NotificationsHost,
  Overflow,
  PaletteEvent,
  PowerEvent,
  ProgressNode,
  RequestId,
  ResizedEvent,
  Result,
  SecretRef,
  SecretsHost,
  SemanticColorToken,
  SettingsEvent,
  SliderNode,
  SpacerNode,
  StateEvent,
  StateHost,
  StateMutation,
  StateSnapshot,
  TextInputNode,
  TextNode,
  ThemeEvent,
  ThemeHost,
  ThemeInfo,
  TimerEvent,
  ToggleNode,
  UnmountedEvent,
  ViewNode,
  ViewStyle,
  ViewTree,
  WallpaperEvent,
  WallpaperHost,
  WallpaperInfo,
  WallpaperMode,
  WallpaperRequest,
  WallpaperRequestReason,
  WallpaperResultEvent,
  WallpaperSetRequest,
  WallpaperSource,
  WallpaperTarget,
  WallpaperTargetKind,
  WatchRegistration,
  WorkspaceEvent,
  WorkspaceTarget,
} from "./generated/wit.ts";
export { err, ok } from "./generated/wit.ts";

export * from "./data.ts";
export * from "./builder/index.ts";
export * from "./host.ts";
export * from "./extension.ts";
export * from "./manifest/index.ts";
