[package]
name = "shilpo-capture"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[features]
default = []
ocr = ["dep:tesseract", "dep:leptonica-sys"]

[dependencies]
serde.workspace = true
chrono.workspace = true
anyhow.workspace = true
tracing.workspace = true
image.workspace = true
arboard = { version = "3", features = ["wayland-data-control"] }
wayland-client.workspace = true
wayland-backend.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true

memfd = "0.6"

tesseract = { version = "0.15", optional = true }
leptonica-sys = { version = "0.4", optional = true }

[dev-dependencies]
tempfile = "3"
