[package]
name = "shilpo-theme-daemon"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
shilpo-ui = { workspace = true }

zbus = { workspace = true }
ashpd = { workspace = true }
futures-lite = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
schemars = { workspace = true }
mcu-material-color = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
