[package]
name = "shilpo-ext-sdk"
version = "0.1.0"
edition.workspace = true
publish = true
description = "Official Rust SDK for developing sandboxed Shilpo desktop extensions"
license = "Apache-2.0"
repository = "https://github.com/sayeed205/shilpo"
readme = "README.md"
keywords = ["shilpo", "extension", "sdk", "wasm", "desktop"]
categories = ["wasm", "gui", "api-bindings"]

[dependencies]
wit-bindgen = { workspace = true }
