pub mod audio;
pub mod bluetooth;
pub mod caffeine;
pub mod clock;
pub mod media;
pub mod network;
pub mod perf_media_capsule;
pub mod pill_strip;
pub mod running_apps;
pub mod settings;
pub mod status_toggles_capsule;
pub mod sysinfo;
pub mod window_info_capsule;
pub mod workspaces;

pub use audio::AudioWidget;
pub use bluetooth::BluetoothWidget;
pub use caffeine::CaffeineWidget;
pub use clock::{ClockWidget, DateWidget};
pub use media::MediaWidget;
pub use network::NetworkWidget;
pub use perf_media_capsule::PerfMediaCapsule;
pub use running_apps::RunningAppsWidget;
pub use settings::SettingsWidget;
pub use status_toggles_capsule::StatusTogglesCapsule;
pub use sysinfo::SysInfoWidget;
pub use window_info_capsule::WindowInfoCapsule;
pub use workspaces::WorkspacesWidget;
